version: '3'
services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - pos_net
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-q',
          '-d',
          '${DB_DATABASE}',
          '-U',
          '${DB_USERNAME}',
        ]
      retries: 3
      timeout: 5s

  # pos:
  #   build:
  #     context: .
  #     target: '${APP_ENV:-production}'
  #   container_name: pos
  #   restart: unless-stopped
  #   volumes:
  #     - .:/project
  #   ports:
  #     - '${APP_PORT:-3000}:3000'
  #   environment:
  #     NODE_ENV: production
  #   depends_on:
  #     - postgres
  #   networks:
  #     - pos_net

networks:
  pos_net:
    driver: bridge
